spring:
  datasource:
    url: jdbc:mysql://localhost:3306/datajpa?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Coco123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
#        one-indexed-parameters: true # index 1부터 시작, but pageNumber는 그대로 0부터 시작

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace # parameter 값 보기

decorator:
  datasource:
    # p6spy 설정 적용
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j